name: ci-development

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./search_api
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: latest

      - name: Install dependencies
        run: uv sync

      - name: Lint with ruff
        run: uv run ruff check .

      - name: Format check with black
        run: uv run black --check .

      - name: Type check with mypy
        run: uv run mypy src/ --ignore-missing-imports

      - name: Run tests with pytest
        run: uv run pytest

      - name: Security check with bandit
        run: uv run bandit -r src/ -f json -o bandit-report.json || true

      - name: Upload security report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: security-report
          path: bandit-report.json
