name: ci-development

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

permissions:
  contents: read
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./search_api

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: latest

      - name: Cache uv dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/uv
            .venv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install dependencies
        run: uv sync --dev

      - name: Verify tools installation
        run: |
          uv run ruff --version
          uv run black --version
          uv run mypy --version
          uv run pytest --version
          uv run bandit --version

      - name: Lint with ruff
        run: uv run ruff check .

      - name: Format check with black
        run: uv run black --check .

      - name: Type check with mypy
        run: uv run mypy src/ --ignore-missing-imports

      - name: Run tests with pytest
        run: uv run pytest

      - name: Security check with bandit
        run: uv run bandit -r src/ -f json -o bandit-report.json || true

      - name: Upload security report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-report
          path: search_api/bandit-report.json   # ルート基準で明示
          if-no-files-found: warn               # 必要なら error に
          retention-days: 7
